import { ResponseCodeEnum } from '../../pbweb/ResponseCode_pb'

/**
 * @module utils
 */

/**
 *
 * enumKeyByValue returns an enum key, given the enum and an enum value.
 * @param {*} enumObject
 * @param {number} value
 */
function enumKeyByValue(enumObject, value) {
    return Object.keys(enumObject).find(key => enumObject[key] === value)
}

/**
 *
 * friendlyHederaResponseCodeEnum function gets the key given the specific value.
 * @param {number} value - value is the specific value in ResponseCodeEnum generated by protobuf.
 */

function friendlyHederaResponseCodeEnum(value) {
    let keyname = enumKeyByValue(ResponseCodeEnum, value)
    let keynameArray = keyname.split('_')
    let processedArray = keynameArray
        .map(k => k.toLowerCase())
        .map(k => capitalize(k))
    let result = processedArray.join(' ')
    return result
}
/**
 *
 * @param {string} str
 */
function capitalize(str) {
    return str.charAt(0).toUpperCase() + str.substr(1)
}

// convert hex string to Uint8Array
const hexStringToUint8Array = hexString => {
    return new Uint8Array(
        hexString.match(/.{1,2}/g).map(function(_byte) {
            return parseInt(_byte, 16)
        })
    )
}

export { enumKeyByValue, friendlyHederaResponseCodeEnum, hexStringToUint8Array }
